sudo: false
language: node_js
node_js:
- node
script: npm run build
deploy:
- provider: firebase
  skip_cleanup: true
  on: master
  token:
    secure: Epe61Gw15ge3kbuBDkjYUcX/zij/XPt2fwZi1GggmYmpycwZHpE/bz95k+ucJUpzqCYQUpY7/A7s30foDw28lrE+LP1q4rGPYvYLnVGqhpevBiKAZLwytkomWgzwjULq/sJC/6J/VmftPatgccvQT3DpohbMWA/mHK/4KbcY/lNB9rDJjDXwlcPGbrNTAOa1pFDEo46cAUkY7P+Tdlc1TxvRfefiJV3IivriKptD6zmq6tYlUbLss9dNkjEGgn95r5t/1EPr7fv2fxNkxesRMQwg7VGXWqZ3XrcyLBkRaNVxO51ah0srY6S7WpoGG3gUDBrFGls7YCm9tW/AYlNssVrL7TXcYa6u8TnU9sNcefCr1wgCiA4d2VndBles232NF0WGjGi7OKTRgd+dSuq231ONuraY7TPsmoSAytGIaT3K74wRIWzljFFpQuzI+c8ibz/RolZmbp1nXzuskB2S6KvpAZsaer6rZKl0yeo97TH4efvlkruWRLUD3IDhMC5YfPsxZ6lzD36KnS5++K78hpPVDrn53KoeXSU1LFp3zqyE307zCD3R47vTvqW5ERyUyaG/n8RNQUA7Zm0Dnp5xSXEwDtNFx5Bktcc15n3o/i7QktDBSqlVGl76q8o4Nz21bjkEWjTnCJZxp0RjflyhXkh4I0gp5NDwjw7npbW2W4g=
