sudo: false
language: node_js
node_js:
  - node
deploy:
  - provider: firebase
    skip_cleanup: true
    on: master
    token:
      secure: "bLYrq+I7qbPRiM5v6wh6KX2v9aNZaRyRbxPor6FQXt3qcZof7HMPjWGfv4RhQiAH+X6B/7vs4qX6+ZhJisTrk2ElBLfvnI3n9OJFfI9Ptwrd2MzUg3Ya300eTRra+6vEKp807T3yn42zLPQqzzuhFGdjZPsfzmSCzFQUUI1c4Z7VZJU1SkkVte/jKwsz/yRCg8vuSLhPbpaWAnZBfdx+98Y4JNDa+SxzB/aTGsi4UsGa/TTUIdl2qL3ipNJo8wfJhu8oYkZQU9dfsQ+Jnx7nsHJD068xv242excyZZgUdYf3QonoCVqLGD98/P+wC720wEAWJ6TD8O4J1tY9EK4pxfdwfH0/sOPiLK5rIW9afVlu5u9rUwtKlIqm7eLUcB52VRVXQnbBSK1kg80OmIVRZFL/XEPxqYEUpoAEeaaihzX2gs8y/stHqmV8cBmbkIJLeUdrJoBXqZ2jAaarRe7ULEismPNWdXDbfJd52EHrJKCNyRsDPZrqBnjFGU7t+o7OKbF2CLQ+kc65xORQV7GnsfVr6auPIe601P91OjXMOA0L9Zx8IazpDBkn+8opWKDhG6SY8S+EbTBKRDn0rQk5QwDOsV02wrawjfIgoAaqHQEJFS8y56Lg62EMnzAUxm52/k16KOK6i5I6xfAH38N9F5Xw6eTbdBp3XnJt+xaryj0="
